/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app/new'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppProjectIdRouteImport } from './routes/_authenticated/app/project/$id'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta/callback'
import { Route as AuthenticatedAppProjectIdReviewRouteImport } from './routes/_authenticated/app/project/$id.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectIdRoute =
  AuthenticatedAppProjectIdRouteImport.update({
    id: '/app/project/$id',
    path: '/app/project/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta/callback',
  path: '/api/public/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppProjectIdReviewRoute =
  AuthenticatedAppProjectIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAppProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/t/$slug': typeof TSlugRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/project/$id': typeof AuthenticatedAppProjectIdRouteWithChildren
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/app/project/$id/review': typeof AuthenticatedAppProjectIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/t/$slug': typeof TSlugRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/project/$id': typeof AuthenticatedAppProjectIdRouteWithChildren
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/app/project/$id/review': typeof AuthenticatedAppProjectIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/t/$slug': typeof TSlugRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/project/$id': typeof AuthenticatedAppProjectIdRouteWithChildren
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/_authenticated/app/project/$id/review': typeof AuthenticatedAppProjectIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/t/$slug'
    | '/app/new'
    | '/app/settings'
    | '/app/'
    | '/app/project/$id'
    | '/api/public/meta/callback'
    | '/app/project/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/t/$slug'
    | '/app/new'
    | '/app/settings'
    | '/app'
    | '/app/project/$id'
    | '/api/public/meta/callback'
    | '/app/project/$id/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/t/$slug'
    | '/_authenticated/app/new'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/project/$id'
    | '/api/public/meta/callback'
    | '/_authenticated/app/project/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TSlugRoute: typeof TSlugRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/project/$id': {
      id: '/_authenticated/app/project/$id'
      path: '/app/project/$id'
      fullPath: '/app/project/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta/callback': {
      id: '/api/public/meta/callback'
      path: '/api/public/meta/callback'
      fullPath: '/api/public/meta/callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/project/$id/review': {
      id: '/_authenticated/app/project/$id/review'
      path: '/review'
      fullPath: '/app/project/$id/review'
      preLoaderRoute: typeof AuthenticatedAppProjectIdReviewRouteImport
      parentRoute: typeof AuthenticatedAppProjectIdRoute
    }
  }
}

interface AuthenticatedAppProjectIdRouteChildren {
  AuthenticatedAppProjectIdReviewRoute: typeof AuthenticatedAppProjectIdReviewRoute
}

const AuthenticatedAppProjectIdRouteChildren: AuthenticatedAppProjectIdRouteChildren =
  {
    AuthenticatedAppProjectIdReviewRoute: AuthenticatedAppProjectIdReviewRoute,
  }

const AuthenticatedAppProjectIdRouteWithChildren =
  AuthenticatedAppProjectIdRoute._addFileChildren(
    AuthenticatedAppProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppProjectIdRoute: typeof AuthenticatedAppProjectIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppProjectIdRoute: AuthenticatedAppProjectIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TSlugRoute: TSlugRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
